title: Help a Jew. Help the Holy Land
tagline: Fighting the System for Jews Left in the Cold
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  “Help a Jew — Help the Holy Land” is a group of dedicated legal professionals who want
  to help those who have been denied their right to return to the Holy Land
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


# Build settings

markdown: kramdown

gems:
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
    - package.json
    - node_modules
    - .idea

permalink: /:title


